<?php

namespace Longman\TelegramBot\Commands\UserCommands;

use common\botHelpers\CommonHelper;
use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Entities\KeyboardButton;
use Longman\TelegramBot\Request;
use Yii;

class ChatCommand extends UserCommand
{
    protected $name = 'chat';                      // Your command's name
    protected $description = 'A command for chatting'; // Your command description
    protected $usage = '/chat';                    // Usage of your command
    protected $version = '1.0.0';                  // Version of your command

    public function execute()
    {
        $message = $this->getMessage();            // Get Message object

        $chat_id = $message->getChat()->getId();   // Get the current Chat ID

        $keyboards = new Keyboard(
            [Yii::t('main', 'New User')],
            [Yii::t('main', 'Block User')]
        );

        $keyboards = $keyboards
            ->setResizeKeyboard(true)
            ->setOneTimeKeyboard(true);

        $data = [                                  // Set up the new message data
            'chat_id' => $chat_id,                 // Set Chat ID to send the message to
            'text'    => Yii::t('main', 'Click the "New conversation partner" button to start')
            . PHP_EOL . Yii::t('main', 'Click the "Block conversation partner" button to block'), // Set message to send
            'reply_markup' => $keyboards
        ];

        return Request::sendMessage($data);        // Send message!
    }

    public function preExecute()
    {
        CommonHelper::initialize($this->update);
        return parent::preExecute(); // TODO: Change the autogenerated stub
    }
}