<?php

namespace Longman\TelegramBot\Commands\UserCommands;

use common\botHelpers\CommonHelper;
use common\botHelpers\UserHelper;
use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Entities\KeyboardButton;
use Longman\TelegramBot\Request;
use Yii;

class RussianCommand extends UserCommand
{
    protected $name = 'russian';                      // Your command's name
    protected $description = 'A command for changing language to russian'; // Your command description
    protected $usage = '/russian';                    // Usage of your command
    protected $version = '1.0.0';                  // Version of your command

    public function execute()
    {
        Yii::$app->language = 'ru';
        $message = $this->getMessage();            // Get Message object

        $chat_id = $message->getChat()->getId();   // Get the current Chat ID

        $keyboards = new Keyboard(
            [Yii::t('main', 'Female')],
            [Yii::t('main', 'Male')]
        );

        $keyboards = $keyboards
            ->setResizeKeyboard(true)
            ->setOneTimeKeyboard(true);

        $data = [                                  // Set up the new message data
            'chat_id' => $chat_id,                 // Set Chat ID to send the message to
            'text' => 'Пожалуйста, выберите Ваш пол', // Set message to send
            'reply_markup' => $keyboards
        ];
        UserHelper::changeLanguageUser($chat_id, 'ru');
        return Request::sendMessage($data);        // Send message!
    }

    public function preExecute()
    {
        CommonHelper::initialize($this->update);
        return parent::preExecute(); // TODO: Change the autogenerated stub
    }
}