<?php

namespace Longman\TelegramBot\Commands\UserCommands;

use common\botHelpers\CommonHelper;
use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Entities\KeyboardButton;
use Longman\TelegramBot\Request;

class StartCommand extends UserCommand
{
    protected $name = 'start';                      // Your command's name
    protected $description = 'A command for start'; // Your command description
    protected $usage = '/start';                    // Usage of your command
    protected $version = '1.0.0';                  // Version of your command

    public function execute()
    {
        $message = $this->getMessage();            // Get Message object

        $chat_id = $message->getChat()->getId();   // Get the current Chat ID

        $keyboards = new Keyboard(
            ["O'zbekcha", 'Русский']
        );

        $keyboards = $keyboards
            ->setResizeKeyboard(true)
            ->setOneTimeKeyboard(true);

        $data = [                                  // Set up the new message data
            'chat_id' => $chat_id,                 // Set Chat ID to send the message to
            'text'    => 'Iltimos, tilni tanlang' . PHP_EOL . "Пожалуйста, выберите язык", // Set message to send
            'reply_markup' => $keyboards
        ];

        return Request::sendMessage($data);        // Send message!
    }

    public function preExecute()
    {
        CommonHelper::initialize($this->update);
        return parent::preExecute(); // TODO: Change the autogenerated stub
    }
}